### ISSUE TITLE
version conflict with mock

### ISSUE THREAD

**Issue by altaurog** [mw44118/pitz#3]
Tried the following:
    sudo pip install git+git://github.com/mw44118/pitz

It seems to work, but when I try to run a command, it fails with following traceback:

```
test 17:13 1028 $ pitz-setup
Traceback (most recent call last):
  File "/usr/bin/pitz-setup", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.5/site-packages/distribute-0.6.10-py2.5.egg/pkg_resources.py", line 2659, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.5/site-packages/distribute-0.6.10-py2.5.egg/pkg_resources.py", line 550, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (mock 0.7.0b3 (/usr/lib/python2.5/site-packages), Requirement.parse('mock==0.4'))
```

**Comment by mw44118** [comment]
I know exactly what this is from, and I'll fix it tonight.  Thanks for the report!

I had no idea anyone uses this!

**Comment by altaurog** [comment]
Glad to be of help.  I myself have no idea if I'll use it or not.  I found it here http://stackoverflow.com/questions/81698/

It looks rough, and I'll have to dig around a bit in code to understand it, but if the agile bit is functional, I may find it useful.  I'm primarily interested in time-tracking functionality and hope to roll my own estimation tool a la Joel Spolsky's EBS.

**Comment by mw44118** [comment]
OK, now try an install again.

Destroy everything from before.

**Comment by altaurog** [comment]
seems to work

```
~ 14:35 1001 $ sudo pip uninstall -y mock decorator clepy jinja2 multiprocessing pitz tempita
~ 14:35 1002 $ sudo pip install git+git://github.com/mw44118/pitz
~ 14:36 1003 $ pitz-help
    pitz-abandon-task          Abandon a task                              
    pitz-add-tag               Add a tag to the project                    
    pitz-add-task              No description                              
    pitz-comment               Store a comment on an entity                
    pitz-components            All components in the project               
    pitz-edit                  Edit an attribute's value                   
    pitz-estimates             All estimates in the project                
    pitz-everything            Everything in the project                   
    pitz-finish-task           Finish a task                               
    pitz-milestones            All milestones in the project               
    pitz-my-todo               My todo list                                
    pitz-pause-task            Pause a task                                
    pitz-people                All people in the project                   
    pitz-prioritize-above      Set frag1['pscore'] to frag2['pscore'] + 1  
    pitz-prioritize-below      Set t1['pscore'] to t2['pscore'] - 1        
    pitz-recent-activity       10 recent activities                        
    pitz-refresh-pickle        Rebuild the pickle file from the yaml files.
    pitz-setup                 Start a new project                         
    pitz-shell                 Start an ipython session after loading in a ...
    pitz-show                  Show a custom view of one entity (detailed b...
    pitz-start-task            Begin a task                                
    pitz-statuses              All statuses in the project                 
    pitz-tags                  All tags in the project                     
    pitz-tasks                 All tasks in the project                    
    pitz-todo                  List every unstarted and started task in the...
    pitz-unassign-task         Take this task off somebody's list of stuff ...
```

**Comment by mw44118** [comment]
I'll close the ticket.  After you use the app, I'd love to hear your thoughts.  Maybe we can chat online or exchange a few emails.

Matt
